### ISSUE TITLE
Detect 2 pupils

### ISSUE THREAD

**Issue by s8sun** [pupil-labs/pupil-detectors#14]
Hi, how can I use Detector2D() to detect 2 pupils in one image? 
Is there any suggested way of implementing this? Thanks

**Comment by pfaion** [comment]
HI @s8sun, the detector does not support this type of detection.
What you try to do is detect one pupil and then mask the image where you detected the first pupil (e.g. by painting a black/white rectangle over it) and run the detection again.

**Comment by papr** [comment]
Alternatively, you can also pass a [region of interest](https://github.com/pupil-labs/pupil-detectors/blob/master/src/pupil_detectors/utils.py#L15) to the image in which the detector will try to extract the pupil ellipse. @pfaion is right though. The algorithm is not meant to detect pupils within a face image but a closeup image of the eye.
