### ISSUE TITLE
Documentation of Detect2D options

### ISSUE THREAD

**Issue by marklescroart** [pupil-labs/pupil-detectors#16]
Hello, thanks for the very useful code. I'm looking for some guidance regarding the options that can be fed to the Detect2D class as a properties dict. I see them enumerated in the code (here: https://github.com/pupil-labs/pupil-detectors/blob/master/src/pupil_detectors/detector_2d/detector_2d.pyx), but I haven't yet found any help on them anywhere. Some seem straightforward (e.g.  `pupil_size_min`) but others (e.g. `ellipse_roundness_ratio`) don't. Is the latter a minimum ratio between the two axes, perhaps? In general, just looking for an explanation of parameters to tweak given our specific eye data. Thanks for your time.

**Comment by papr** [comment]
Please see this paper for a description of the algorithm: https://arxiv.org/pdf/1405.0006.pdf

Please note that we tuned most of the parameters to work well with all eye images. The parameters that are most dependent on the image are: `intensity_range`, `pupil_size_max`, and `pupil_size_min`. An additional important factor for good pupil detection is the contrast between pupil and remaining image. This can be controlled best via image exposure time during the recording.
