### ISSUE TITLE
ImportError: DLL load failed while importing detector_2d

### ISSUE THREAD

**Issue by wwdok** [pupil-labs/pupil-detectors#24]
I build pupil-detectors on WIndows, it seems everything is OK.
![image](https://user-images.githubusercontent.com/43233772/180016784-325a5331-ffa1-47e5-a82c-b6d8ae905fb9.png)

But when i run the example code, it throw error:
![image](https://user-images.githubusercontent.com/43233772/180017154-abf36bd2-7eb0-4d55-9b9f-667e26b93b25.png)

**Comment by papr** [comment]
Please use https://github.com/lucasg/Dependencies on the generated `detector_2d.*` file (not 100% sure about the file extension on Windows, might be dll, too)

**Comment by papr** [comment]
@wwdok Hi! Please follow these steps:
1. Unpack the downloaded file to an isolated folder, e.g. in your downloads
2. Runthe DependenciesGui.exe
3. Drag and drop the `detector_2d...pyd` onto the newly opened window
4. The window should list its dependencies and show the missing ones in red

**Comment by papr** [comment]
@wwdok Could you please expand the entries in the top left and check if the sub-dependencies are present as well.

If everything is present, could you please restart your computer and try running the code again. Sometimes, programs on Windows do not update the dependency lookup correctly. Restarting clears the cache.

Do you still get the same error? If this is the case, could you please translate the non-english parts of the error message for me?

**Comment by papr** [comment]
Hi, this issue is related to https://stackoverflow.com/a/59333711

**Comment by papr** [comment]
Please repeat that call with the library in which the `opencv_world345.dll` is located.

**Comment by papr** [comment]
Nice!
