### ISSUE TITLE
Detector2D detection parameters

### ISSUE THREAD

**Issue by KarlKulator** [pupil-labs/pupil-detectors#6]
Hi,

the performance of Detector2D on LPW dataset seems to have problems with parameters where only the pupil_size_max and pupil_size_min were adapted.

I used single image Detector2D with the following parameters:
```
    detector = Detector2D({'2d': {
        "coarse_detection": True,
        "coarse_filter_min": 128,
        "coarse_filter_max": 280,
        "intensity_range": 23,
        "blur_size": 5,
        "canny_treshold": 160,
        "canny_ration": 2,
        "canny_aperture": 5,
        "pupil_size_max": 200,
        "pupil_size_min": 60,
        "strong_perimeter_ratio_range_min": 0.6,
        "strong_perimeter_ratio_range_max": 1.1,
        "strong_area_ratio_range_min": 0.8,
        "strong_area_ratio_range_max": 1.1,
        "contour_size_min": 5,
        "ellipse_roundness_ratio": 0.09,
        "initial_ellipse_fit_treshhold": 4.3,
        "final_perimeter_ratio_range_min": 0.5,
        "final_perimeter_ratio_range_max": 1.0,
        "ellipse_true_support_min_dist": 3.0,
        "support_pixel_ratio_exponent": 2.0,
    }})
    result = detector.detect(gray)
```
And this high res image:
![glassesEye](https://user-images.githubusercontent.com/7453230/70455189-21ae7580-1aac-11ea-8dfb-98f81540860e.png)

The detector did not find the pupil at all.

Another example is a lower res image with the following parameters where also no pupil is found
```
detector = Detector2D({'2d': {
        "coarse_detection": True,
        "coarse_filter_min": 128,
        "coarse_filter_max": 280,
        "intensity_range": 23,
        "blur_size": 5,
        "canny_treshold": 160,
        "canny_ration": 2,
        "canny_aperture": 5,
        "pupil_size_max": 50,
        "pupil_size_min": 15,
        "strong_perimeter_ratio_range_min": 0.6,
        "strong_perimeter_ratio_range_max": 1.1,
        "strong_area_ratio_range_min": 0.8,
        "strong_area_ratio_range_max": 1.1,
        "contour_size_min": 5,
        "ellipse_roundness_ratio": 0.09,
        "initial_ellipse_fit_treshhold": 4.3,
        "final_perimeter_ratio_range_min": 0.5,
        "final_perimeter_ratio_range_max": 1.0,
        "ellipse_true_support_min_dist": 3.0,
        "support_pixel_ratio_exponent": 2.0,
    }})
    result = detector.detect(gray)
```
![remoteEye](https://user-images.githubusercontent.com/7453230/70455450-a1d4db00-1aac-11ea-9702-b7908c3a1292.png)

Is it possible to detect the pupil with different parameters?
Can you tell me which parameters might be most important for tuning here?

**Comment by pfaion** [comment]
Hi @KarlKulator 
I'd recommend enabling the debug view by passing a second image buffer to `.detect()`. This needs to be a color image of the same size as your gray img, e.g. with:
```python
# ...
debug= cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
result = detector.detect(gray, debug)
cv2.imshow("Debug", debug)
```
Can you post a debug image?

**Comment by pfaion** [comment]
Also in general we recommend resizing the images to something along the lines of **320x240**, which will normally result in best performance.

**Comment by KarlKulator** [comment]
Thank you for your help.
Rescaling to 320x240 solved the problem for both images.

I got another image where the detection fails even with 320x240 while the pupil is clearly visible:
![136_x_0_0 png_320x240](https://user-images.githubusercontent.com/7453230/72070567-31f38380-32ea-11ea-94b9-60fc75d76ebc.png)
![136_x_0_0 pngDetector2D](https://user-images.githubusercontent.com/7453230/72070577-33bd4700-32ea-11ea-9575-b82aefcb3f4d.png)

It seems to find the contour of the pupil, but does not take it as support pixels for the ellipse, it takes the edge marked white.

Can you see which parameters can be changed to solve the detection?
I am also thinking about tuning the parameters with a search (,e.g., grid search). Can you recommend which parameters are important and maybe what ranges are reasonable?

**Comment by pfaion** [comment]
I think this is less a problem of the detector parameters, but rather of the input image. The default parameters were tuned already with a grid-search over a large dataset. Some recommendations:

**Constrast**
While the pupil is *clearly visible* for a human, the contrast between the iris and the pupil is actually very low. Normally we recommend to adjust the camera parameters, e.g. exposure time, to receive better images.

**Masking**
Additionally the detectors assume that the pupils are the darkest region in the image. As you can see in the debug image, the top-left and bottom-left corners are also very dark and get thereby detected as potential regions for the pupil. This can throw off the detector. I you have images with dark spots (shadows, glasses, headsets) in the outer region of the image, we recommend using a region-of-interest (ROI) mask to confine the pupil detection to a sub-region of the image. In [Pupil](https://github.com/pupil-labs/pupil) we have a UI for quickly specifying ROIs with the mouse, but here this is a bit cumbersome to do manually. You will essentially have to figure out good pixel values for the ROI by hand. You will be able to see the used ROI in the debug view.
```python
# ...

from pupil_detectors import Roi

# ...

# figure out good values and construct Roi throught one of those:
roi = Roi(x_min=50, y_min=50, x_max=200, y_max=150)
roi = Roi.from_rect(x=50, y=50, width=150, height=100)

result = detector.detect(gray, debug, roi=roi)
```

**Comment by pfaion** [comment]
You can of course run another grid-search to figure out a better parameter-set for your set of images. This might not generalize to future images then though.

**Comment by pfaion** [comment]
I'll close this issue for now, I hope your question got clarified!
If you have another question, feel free to open another issue.
